name: dbldart
description: Discord Bot List API for Dart
version: 0.1.3
homepage: https://github.com/voximity/dbldart
author: vox <0zanfran@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "^0.11.3+16"

dev_dependencies:
  test: ^0.12.0
